# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9c299d1d9e1a43d46f5e0b9213f68b36c379ec6cf25a412b5231073625755f0667ec57359a248c088a35249aa567cad3880067f116778ea886cee8e0d0544354

test:
  secret_key_base: 531e95e86d386d5d0c9dbde412fe1629cf3fb92a65a40d2387f81d29fd2b66d9a1b345095e8e23be5f2a22f4f5b4d5f567586fecbb105e2b0245d9cb558972c6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
